ng generate component assignment
ng generate component class
ng generate component grade
ng generate component instructor
ng generate component major
ng generate component major_class
ng generate component student_class
ng generate component assignment-form
ng generate component class-form
ng generate component grade-form
ng generate component instructor-form
ng generate component major-form
ng generate component major_class-form
ng generate component student_class-form
